global:
  resolve_timeout: 5m
  slack_api_url: <YOUR-SLACK-API-URL>
route:
  group_by: ['namespace', 'job']
  group_interval: 5m
  group_wait: 5m
  receiver: slack
  repeat_interval: 12h
  routes:
#  - match:
#      alertname: InfoInhibitor
#    receiver: 'null'
  - match:
      alertname: Watchdog
    receiver: 'null'
  - match:
      alertname: TargetDown
    recevier: "null"
  - match:
      alertname: etcdMembersDown
    recevier: "null"
  - match:
      alertname: etcdInsufficientMembers
    recevier: "null"
  - match:
      alertname: CPUThrottlingHigh
    recevier: "null"
  - match:
      alertname: AggregatedAPIDown 
    receiver: 'null'
  - match:
      alertname: KubeClientErrors
    receiver: 'null'
  - match:
      alertname: etcdHighNumberOfFailedGRPCRequests
    receiver: 'null'
  - match:
      statefulset: activemq-activemq-artemis-slave
    receiver: 'null'
  - match:
      severity: critical
    receiver: 'slack'
  - match:
      severity: warning
    receiver: 'slack'
  - match:
      severity: info
    receiver: 'null'
  - match:
      severity: none
    receiver: 'null'
  - match:
      alertname: KubeStatefulSetReplicasMismatch
    receiver: 'null'
  - match:
      alertname: KubeDeploymentReplicasMismatch
    receiver: 'null'
  - match:
      alertname: KubeContainerWaiting
    receiver: 'slack'
  - match:
      alertname: KubeJobFailed
    receiver: 'slack'  

receivers:
- name: 'null'
- name: slack
  slack_configs:
  - channel: '<YOUR-CHANNEL-HERE>'
    send_resolved: true
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
    text: |-
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
      *Description:* {{ .Annotations.description }}
      *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
      *Details:*
      {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
      {{ end }}
      {{ end }}
